### ISSUE TITLE
Gets stuck on Destory

### ISSUE THREAD

**Issue by gurjitsk** [Azure/terraform-azurerm-network#14]
Hi 
The destroy gets stuck as below:
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/a0bba555-00000-00000-00006-...oft.Network/virtualNetworks/GSKM-VNET1, 22m11s elapsed)

Can someone help ?

**Comment by dcaro** [comment]
Looks like #3

**Comment by JunyiYi** [comment]
Hi @gurjitsk , thanks for reporting the issue. And I agree with @dcaro to track it in #3 .
