### ISSUE TITLE
Cannot link additional security group rules by ID

### ISSUE THREAD

**Issue by yzhang-myob** [Azure/terraform-azurerm-network#15]
Hi there,

How do you associate new security group rules by network_security_group_id? The security group rules can only associated with security group name.

**Comment by dcaro** [comment]
@yzhang-myob, I have updated the module to not implement security groups therefore giving more freedom on how to use those. The README on PR #16 shows how to do that.

**Comment by yzhang-myob** [comment]
Thanks for this
