### ISSUE TITLE
Travis-CI build failing - az profile not found

### ISSUE THREAD

**Issue by dcaro** [Azure/terraform-azurerm-network#19]
Running terraform 11.1 & azure provider 1.1.0 end to end test fails with the following error
 * provider.azurerm: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

**Comment by yupwei68** [comment]
You need to set environment variables of a service principal, such as` $ARM_SUBSCRIPTION_ID`. And run the command  `docker build --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t azure-network .` to build it.
