### ISSUE TITLE
Subnet network security group example seems flawed

### ISSUE THREAD

**Issue by bfleming-ciena** [Azure/terraform-azurerm-network#23]
Hey there,

I'm running the newest example of setting the subnet to a network security group for SSH.

Reproducing the error.

Run the example on the readme.  Then edit the port on the SSH group, to whatever, 22-23 range.  Apply.

From my experience, what happens is the security group is REMOVED from the subnet.  I think this has something to do with the module code that loops through all subnets and sets the security group id.

**Comment by yupwei68** [comment]
Thanks for opening this issue. There is a PR pending merged to solve your problem, https://github.com/Azure/terraform-azurerm-network/pull/32.
