### ISSUE TITLE
Adding routes

### ISSUE THREAD

**Issue by bfleming-ciena** [Azure/terraform-azurerm-network#24]
What's a recommendation on allowing routes to be given?  I see Azure doesn't let you associate route tables with subnets as a separate function. It has to be done at creation time? That makes this module difficult to use if you need to create custom route tables on your subnet.

**Comment by yupwei68** [comment]
@bfleming-ciena Thanks for opening this issue. Now `route_table_id` in `azurerm_subnet` is Deprecated. You could use `azurerm_subnet_route_table_association` to custom route tables.
