### ISSUE TITLE
Error occurs when testing module

### ISSUE THREAD

**Issue by foreverXZC** [Azure/terraform-azurerm-network#25]
When I am using the current test case and try apply and destroy the module, an error occurs showing that the resource group cannot be found when destroying. It seems that terraform tries to delete one resource group twice and thus the build in travis CI fails eventually.

However, if I change `source = "../../"` to `source = "Azure/network/azurerm"`, the whole process will succeed. Therefore, this demonstrates two problems:
1. The code in GitHub is actually not identical to the newest released version, because the released module works but the code in repo does not.
2. Some other modules are based on network module of version 2.0.0, which is the latest version. If we use the code in GitHub to update the release, this may harm to other modules. For instance, I contributed terratest to compute module and the test case is using network module 2.0.0. If we try to sync up the released network module with code in repo, the test of compute module may fail.

As a result, I would like to provide a plan to solve this problem. First, I revert the repo to version 2.0.0, which is latest released and commonly used. Second, I would like to introduce terratest to network module to run automatic test, just as compute module does.

**Comment by yupwei68** [comment]
@foreverXZC Thanks for your contribution. If no further question, please close this issue.
