### ISSUE TITLE
Issues while changing the address space for virtual network and subnet.

### ISSUE THREAD

**Issue by sunnynazar** [Azure/terraform-azurerm-network#28]
We are using below terraform code.

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.vnet_name}"
  location            = "${var.location}"
  address_space       = ["${var.address_space}"]
  resource_group_name = "${var.resource_group_name}"
  tags                = "${var.tags}"
}

resource "azurerm_subnet" "subnet" {
  name                 = "${var.subnet_names[count.index]}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  resource_group_name  = "${var.resource_group_name}"
  address_prefix       = "${var.subnet_prefixes[count.index]}"
  count                = "${length(var.subnet_names)}"
}

We created virtual network and Subnet with a particular address space.
Post that we decided that there is a need to change the address space for vnet and subnet and during the apply we get an error .

What we see  during the plan is that although we did n't specify any subnet to be created in the resource "azurerm_virtual_network" "vnet" , subnet entries are present in the vnet with the address values which were specified during the initial creation and it does not show that its going to update the new address space for subnet. Thats where the problem is according to me which results in the error.

Terraform will perform the following actions:
  # module.network.azurerm_subnet.subnet[0] will be updated in-place
  ~ resource "azurerm_subnet" "subnet" {
      ~ address_prefix       = "10.20.0.0/24" -> "10.30.0.0/24"
        id                   = "/subscriptions/<sb_id>/resourceGroups/RG-operationNE-DEV/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/subnet-test"
        ip_configurations    = []
        name                 = "subnet-test"
        resource_group_name  = "RG-operationNE-DEV"
        service_endpoints    = [
            "Microsoft.Sql",
            "Microsoft.Web",
        ]
        virtual_network_name = "test-vnet"
    }

  # module.network.azurerm_virtual_network.vnet will be updated in-place
  ~ resource "azurerm_virtual_network" "vnet" {
      ~ address_space       = [
          - "10.20.0.0/16",
          + "10.30.0.0/16",
        ]
        dns_servers         = []
        id                  = "/subscriptions/<sb_id>/resourceGroups/RG-operationNE-DEV/providers/Microsoft.Network/virtualNetworks/test-vnet"
        location            = "northeurope"
        name                = "test-vnet"
        resource_group_name = "RG-operationNE-DEV"
        tags                = {}

        subnet {
            address_prefix = "10.20.0.0/24"
            id             = "/subscriptions/<sb_id>/resourceGroups/RG-operationNE-DEV/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/subnet-test"
            name           = "subnet-test"
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.network.azurerm_virtual_network.vnet: Modifying... [id=/subscriptions/<sb_id>/resourceGroups/RG-operationNE-DEV/providers/Microsoft.Network/virtualNetworks/test-vnet
]

Error: Error Creating/Updating Virtual Network "test-vnet" (Resource Group "RG-operationNE-DEV"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error
: Code="NetcfgInvalidSubnet" Message="Subnet 'subnet-test' is not valid in virtual network 'test-vnet'." Details=[]

  on ../../../modules/network/main.tf line 2, in resource "azurerm_virtual_network" "vnet":
   2: resource "azurerm_virtual_network" "vnet" {

Teerraform verion and provider version details are below.

Terraform v0.12.6
+ provider.azurerm v1.32.1

Please let me know if you need more details.

**Comment by matthewi** [comment]
I'm dealing with a similar change. Have you also provisioned any resources to the vnet/subnet? If so, I don't think you can change it without moving or destroying those resources:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-subnet

**Comment by yupwei68** [comment]
@sunnynazar Thanks for opening this issue. Could you please provide your code of assignment of variables, initial code and update code?
