### ISSUE TITLE
Error occurs when variable vnet_name is declared

### ISSUE THREAD

**Issue by daribei** [Azure/terraform-azurerm-network#29]
Hey guys,

I'm testing this module, but when I declare the variable **vnet_name**, the error below happens.

"Error: Duplicate variable declaration

  on variables.tf line 9:
   9: variable "vnet_name" {

A variable named "vnet_name" was already declared at main.tf:1,1-21. Variable
names must be unique within a module."

My code:
variable "vnet_name" {
  default     = "vnet-test"
}

module "network" {
  source  = "Azure/network/azurerm"
  version = "2.0.0"
    resource_group_name = "myapp"
    location            = "westus"
    address_space       = "10.0.0.0/16"
    subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
    subnet_names        = ["subnet1", "subnet2", "subnet3"]

    tags                = {
                            environment = "dev"
                            costcenter  = "it"
                          }
}

Can you help me?

**Comment by yupwei68** [comment]
Hi @xdanielribeiro, Thanks for opening this issue. You could assign `vnet_name` in module.

```
module "network" {
  source              = "Azure/network/azurerm"
  version             = "2.0.0"
  resource_group_name = "myapp"
  location            = "westus"
  vnet_name           = "vnet-test"
  address_space       = "10.0.0.0/16"
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}
```
