### ISSUE TITLE
terraform destroy get's stuck on module.network.azurerm_virtual_network.vnet

### ISSUE THREAD

**Issue by MichalTaratuta** [Azure/terraform-azurerm-network#3]
When trying to destroy the resources terrafrom gets stuck on `module.network.azurerm_virtual_network.vnet: Still destroying...`

Terraform v0.10.8

**Comment by dtzar** [comment]
I confirmed this still exists with 0.11.0 also.  It is a problem with the resource provider itself: https://github.com/terraform-providers/terraform-provider-azurerm/issues/373

**Comment by rguthriemsft** [comment]
I think this is also preventing the module test from succeeding.

**Comment by yupwei68** [comment]
Thanks for opening this issue. I think it's solved in https://github.com/terraform-providers/terraform-provider-azurerm/issues/373. And I'm going to close this issue.
