### ISSUE TITLE
Upload v3.0.0 to terraform registry

### ISSUE THREAD

**Issue by tecris** [Azure/terraform-azurerm-network#36]
Hi,
Can you please upload v3.0.0 to terraform registry.

thanks

**Comment by yupwei68** [comment]
OK, @tecris thax

**Comment by yupwei68** [comment]
hi @tecris ,the release still not works. Do you have any other ideas?

**Comment by shoepping** [comment]
Hi @yupwei68 
Sorry, I am not familiar how to publish to terraform registry.

**Comment by tecris** [comment]
Hi @yupwei68
Sorry, I am not familiar how to publish to terraform registry.

**Comment by hansarh** [comment]
What's the status on this? hope the new releases can be published  in registry. This is the top module for Azure modules on registry so I'm a bit surprised the newer versions are not published there

**Comment by jonatasbaldin** [comment]
+1 on the status on this issue. The v2 and v3 are quite different and the documentation in the TF Registry already reflects the v3.

**Comment by yupwei68** [comment]
Sorry for the delay the publish in terraform registry. We have contacted Hashicorp. They have worked on it. And we'll release v3.0.1 soon.
