### ISSUE TITLE
Confusion on which module to use

### ISSUE THREAD

**Issue by lanox** [Azure/terraform-azurerm-network#43]
Hi, 

I am sorry if this was asked, but what is the difference between this module and this one [terraform-azurerm-vnet](https://github.com/Azure/terraform-azurerm-vnet) I am asking as I would like to use this module but I am not sure which one repository to use.

I have found the same question been asked here but, nobody responded.

https://github.com/Azure/terraform-azurerm-vnet/issues/8

**Comment by yupwei68** [comment]
Hi @lanox , thanks for opening this issue. Currently the main difference between module `vnet` and `network` is that `vnet` supports nsg and route table assignment while `network` not.

**Comment by lanox** [comment]
> Hi @lanox , thanks for opening this issue. Currently the main difference between module `vnet` and `network` is that `vnet` supports nsg and route table assignment while `network` not.

@yupwei68  thanks for the response, but why are there 2 same projects, that literally do the same things, and almost manages by same people? shouldn't be wiser to archive one and continue with work on the more feature-rich one?

**Comment by yupwei68** [comment]
Hi @lanox thanks for your suggestion. While we could not deprecate the module with big number of users, we'll continue to support and maintain these two modules. And sorry that I'll close this issue.
