### ISSUE TITLE
Separate security group module

### ISSUE THREAD

**Issue by ricoli** [Azure/terraform-azurerm-network#5]
I find the presence of a security group in this module to be quite strange and inflexible. Wouldn't it be better to have a separate module just to deal with security groups and then allow users to associate them to subnets in this module (as a list input) if they so choose? That is also the direction that the AWS folks have gone for: https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/1.5.0

**Comment by dtzar** [comment]
I agree.

**Comment by sebastus** [comment]
A module has value to the extent that it makes writing HCL easier or faster. If the network module is an injected resource group + vnet + subnet, then it's nothing but a thin shell around vnet resource and adds no value. What's the right mix of resources for a network module?

**Comment by ricoli** [comment]
Don't forget DNS configuration too, multiple subnets at once and uniform tagging. That's plenty of value already, in my view.

**Comment by ricoli** [comment]
I would also like to disagree with your remark that the value of a module is such that it "makes writing HCL easier or faster". As described in https://www.terraform.io/intro/getting-started/modules.html: "Modules are used to create reusable components, improve organization, and to treat pieces of infrastructure as a black box."

**Comment by xerespm** [comment]
I agree. :+1:

For example, NSG in GatewaySubnet is not supported, but if you create with this module NSG will be applied. It is not cool.

**Comment by gurjitsk** [comment]
NSG should not be part of this module, for example I only need networks so that I can use the Virtual Appliance instead of NSG's.

**Comment by dcaro** [comment]
@ricoli @xerespm I have just reworked the module to remove the NSG as per this discussion. Pending PR#16 to be approved.
Feel free to suggest further improvements.
Thanks for your patience.

**Comment by dcaro** [comment]
The changes have been merged in v2.0.0 of the module.
Let me know if you have any feedback.

**Comment by ricoli** [comment]
Thanks for the changes :)
I think the same applies to the compute module really, and any news on actually getting a separate Terraform module just for security groups?

**Comment by dtzar** [comment]
https://github.com/Azure/terraform-azurerm-network/pull/16

**Comment by dcaro** [comment]
@ricoli I've added the creation of a module for security groups to our backlog. I don;t have an ETA at this time. Can you open an issue about the compute module? Thanks.
