### ISSUE TITLE
add enforce_private_link_endpoint_network_policies 

### ISSUE THREAD

**Issue by achevalet** [Azure/terraform-azurerm-network#50]
Hi,
Could we add a new optional input to set `enforce_private_link_endpoint_network_policies` on `azurerm_subnet`?
Thanks

**Comment by yupwei68** [comment]
Hi @achevalet Thanks for opening this issue. I'll add this feature into plan, but I could not give an ETA for it. BTW, You're welcome to contribute to this repo too.

**Comment by achevalet** [comment]
Sure, thank you @yupwei68.
