### ISSUE TITLE
v3.3.0 not available from Terraform's registry

### ISSUE THREAD

**Issue by chicken231** [Azure/terraform-azurerm-network#52]
It looks like v3.3.0 was released about 2 weeks ago. But according to Terraform, the latest available is `v3.2.1`.

With this set:
```
module "network" {
  source  = "Azure/network/azurerm"
  version = "3.3.0"
}
```

`terraform init` says:
```
Error: Unresolvable module version constraint

There is no available version of module "Azure/network/azurerm" (network.tf:2)
which matches the given version constraint. The newest available version is
3.2.1.
```

The official page also agrees: https://registry.terraform.io/modules/Azure/network/azurerm/latest

If releases got tagged, I think I could work around this easily, but for now I'll have to clone the repo locally as I need support for `subnet_enforce_private_link_endpoint_network_policies`.

**Comment by yupwei68** [comment]
Hi @chicken231 , thanks for opening this issue. I've resynced the module release.
