### ISSUE TITLE
Integration Tests Failing

### ISSUE THREAD

**Issue by lhaig** [Azure/terraform-azurerm-network#57]
I have noticed that the test are failing with incorrect credentials errors.

Is there a way this can be updated so that the test scan complete?

**Comment by yupwei68** [comment]
Hi @lhaig , thanks for opening this issue. It's caused by the operation timeout. I'll fix it soon.

**Comment by yupwei68** [comment]
Hi @lhaig , thanks for opening this issue. We have fixed the CI test.
