### ISSUE TITLE
Resource Group variable should accept entire resource_group object

### ISSUE THREAD

**Issue by troyready** [Azure/terraform-azurerm-network#58]
Passing in the resource_group name only and relying on `depends_on` on the module [causes lifecycle issues](https://github.com/hashicorp/terraform/issues/26074) for the resources in this module. E.g., if the [tags on the resource group are changed then the subnets will be replaced](https://github.com/Azure/terraform-azurerm-vnet/issues/41) (because of a new computed `location` attribute on the resource group data_source in the module).

[Martin's recommendation](https://github.com/hashicorp/terraform/issues/26074#issuecomment-693696693) is that:
> In current versions of Terraform we generally recommend that a specific configuration should either be managing an object or reading the object using a date resource, but not both at the same time.

He then details what a variable design would be that avoids this issue:

```hcl
variable "resource_group" {
  type = object({
    name     = string
    location = string
  })
}
```
Able to be consumed like:
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "my-resources"
  location = "West Europe"
}

module "network" {
  source = "Azure/network/azurerm"

  resource_group  = azurerm_resource_group.test
  address_space   = "10.0.0.0/16"
  subnet_prefixes = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names    = ["subnet1", "subnet2", "subnet3"]

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}
```

This would obviously be a breaking change to the module (requiring a major version bump), but it wouldn't be hazardous to users: accidental upgrades would cause an error that the new variable is missing, allowing them to update the variable and continue using the module.

**Comment by lonegunmanb** [comment]
Thanks @troyready for raising this issue and my apology for this late reply, we've brought this feature via #78 so I'm closing this issue now. Thanks for your contribution!
