### ISSUE TITLE
Service delegation

### ISSUE THREAD

**Issue by gevraud** [Azure/terraform-azurerm-network#64]
Hello,

I wanted to use this module to create Azure RedHat Openshift but it seems the service delegation isn't there (https://docs.microsoft.com/en-us/azure/virtual-network/subnet-delegation-overview)

Is it possible to add it ?

Regards

**Comment by lonegunmanb** [comment]
Hi @gevraud , apology for this late reply, this feature has been brought by #81 so I'm closing this issue now.
