### ISSUE TITLE
Minimum supported Terraform version

### ISSUE THREAD

**Issue by don-code** [Azure/terraform-azurerm-network#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The module is not clear on what the actual required minimum version of Terraform is.

1. The `versions.tf` file specifies that Terraform 1.2 or higher will work.
2. The `README.md` has instructions for running on Terraform 0.12, which would suggest that 0.12 and higher would all work.
3. The `variables.tf` file makes use of `optional()`, which requires Terraform 1.3 or higher.

This leads me to believe the actual minimum version is 1.3, in which case I'd recommend updating `versions.tf` to reflect that, and removing references to 0.12 and 0.13 from the README.

I'm happy to make this change if a maintainer agrees that supported versions actually are 1.3+.

### New or Affected Resource(s)/Data Source(s)

n/a

**Comment by lonegunmanb** [comment]
Thanks @don-code for raising this issue, you're right! Since we've used `optional` for `object` type, the actual required Terraform version should be `1.3`. I'll be happy to accept your pr if you'd like to submit one to fix this issue 😄
